In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("C:/Users/Radha/OneDrive/Desktop/FBS/Datasets-20261026T112107Z-1-001/Datasets/student_10.csv")
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     object
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 532.0+ bytes

In [5]:
data.describe()

        Student ID      Class  Study hrs  Percentage
count     7.000000  10.000000   8.000000    7.000000
mean   1006.000000  11.100000   4.375000   72.142857
std       3.464102   0.875595   3.020761   15.236235
min    1001.000000  10.000000   0.000000   50.000000
25%    1003.500000  10.250000   2.750000   60.000000
50%    1007.000000  11.000000   4.000000   80.000000
75%    1008.500000  12.000000   6.000000   82.500000
max    1010.000000  12.000000  10.000000   90.000000

In [7]:
data.shape

(10, 5)

In [8]:
type(data)

pandas.core.frame.DataFrame

In [9]:
data.size

50

In [10]:
data.head()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN

In [11]:
data.head(3)

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0

In [12]:
data.tail()

         Date  Student ID  Class  Study hrs  Percentage
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [13]:
data.isna().sum()

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [14]:
data.dropna()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
9  12-07-2021      1010.0     12        6.0        85.0

In [18]:
data.dropna(inplace= True,axis =1)
data

         Date  Class
0  01-07-2021     10
1  02-07-2021     10
2  03-07-2021     10
3  06-07-2021     11
4  07-07-2021     11
5  08-07-2021     11
6  09-07-2021     12
7  10-07-2021     12
8  11-07-2021     12
9  12-07-2021     12

In [19]:
data = pd.read_csv("C:/Users/Radha/OneDrive/Desktop/FBS/Datasets-20261026T112107Z-1-001/Datasets/student_10.csv")

In [20]:
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [21]:
data['Class']

0    10
1    10
2    10
3    11
4    11
5    11
6    12
7    12
8    12
9    12
Name: Class, dtype: int64

In [28]:
data['Class'].sum()

111

In [26]:
data['Class'].unique()

array([10, 11, 12], dtype=int64)

In [29]:
data['Class'].mean()

11.1

In [30]:
data[data['Study hrs'] >4.0]

         Date  Student ID  Class  Study hrs  Percentage
1  02-07-2021      1002.0     10        6.0        80.0
5  08-07-2021         NaN     11       10.0         NaN
9  12-07-2021      1010.0     12        6.0        85.0

In [31]:
data.columns

Index(['Date', 'Student ID', 'Class', 'Study hrs', 'Percentage'], dtype='object')

In [32]:
data['Class'].value_counts()

Class
12    4
10    3
11    3
Name: count, dtype: int64

In [34]:
data['Study hrs'].agg(['min', 'max','sum'])

min     0.0
max    10.0
sum    35.0
Name: Study hrs, dtype: float64